# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-MimeInfo
version:      0.10
version_from: MimeInfo.pm
installdirs:  site
requires:
    Carp:                          0
    Exporter:                      0
    Fcntl:                         0
    File::BaseDir:                 0
    Pod::Usage:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
