---
name: File-MimeInfo
version: 0.14
author:
  - 'Jaap Karssenberg <pardus@cpan.org>'
abstract: Module to determine file types
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  Fcntl: 0
  File::BaseDir: 0
  Pod::Usage: 0
recommends:
  File::DesktopEntry: 0
provides:
  File::MimeInfo:
    file: lib/File/MimeInfo.pm
    version: 0.14
  File::MimeInfo::Applications:
    file: lib/File/MimeInfo/Applications.pm
    version: 0.03
  File::MimeInfo::Magic:
    file: lib/File/MimeInfo/Magic.pm
    version: 0.14
  File::MimeInfo::Rox:
    file: lib/File/MimeInfo/Rox.pm
    version: 0.2
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
